### ISSUE TITLE
console library 

### ISSUE THREAD

**Issue by id4ehsan** [mrfearless/Dll2Def#1]
in Dll2Def.inc line 16, 17 console library has been used which i couldn't find it anywhere in web 
i tried to compile it for 32bit OS because the executable didn't work on my XP VM
can you provide console.lib and console.inc or 32bit release of it please?

**Comment by mrfearless** [comment]
Hi, thanks. I have updated the readme to point to the console x86 library source, which can be found in the libraries repository along with other libraries that I occasionally use. The console page is here: https://github.com/mrfearless/libraries/tree/master/Console and the releases for most libs including the console x86 can be found at https://github.com/mrfearless/libraries/releases
